import { Inter } from "next/font/google";
import './global.css';

import Sidebar from "@/components/sidebars/Sidebar";
import Header from "@/components/header/Header";
import { Toaster } from "sonner";

import TokenProvider from "@/contexts/TokenProvider";
import ToggleProvider from "@/contexts/ToggleProvider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Airbnb - Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const access_token = cookies().get("access-admin")?.value;
    const refresh_token = cookies().get("refresh-admin")?.value;

    return (
        <html lang="en">
            <body className={ `${ inter.className } bg-[#FBF4F5] style-scrollbar style-scrollbar-body`}>
                <TokenProvider tokens={{ access_token, refresh_token }}>
                    <ToggleProvider info={{ isOpen: false }}>
                        <div className="flex items-start">
                            <Sidebar />

                            <div className="pt-[30px] px-[20px] w-full">
                                <Header />
                                {children}
                            </div>
                        </div>

                        <Toaster />
                    </ToggleProvider>
                </TokenProvider>
            </body>
        </html>
    );
}
